server:
  port: 8080

# Spring Actuator 관련된 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

# Spring Cloud Gateway 는 아래와 같이 주소 설정만 해둬도 게이트웨이 기본적인 기능은 제공한다.
# 그래서 이는 구현할 게 많지는 않다. 다만 이에 대해 어떻게 작동하는지 파악은 하고 있어야 할 거 같다.
spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<path>.*),/$\{path}
        - id: order-service
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}